name: WakaTime Readme

on:
  schedule:
    # Se ejecuta a las 00:00 UTC cada día
    - cron: '0 0 * * *'
  workflow_dispatch: # Esto permite que lo ejecutes manualmente para probar

jobs:
  update-readme:
    name: Actualizar WakaTime Stats
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4 # Versión actualizada del checkout
      
      - uses: athul/waka-readme@master # Usamos @master para evitar el error de versión
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: "->"
          TIME_RANGE: last_7_days
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
